version: '2'
services:
  onduty:
    image: onduty:latest
    command: bundle exec puma -p 9292
    environment:
      - ONDUTY_MONGODB_HOST=mongodb:27017
      #- RACK_ENV=production
    ports:
      - 9292:9292
    links:
      - mongodb:mongodb
  mongodb:
    image: mongo:3.4.4
    command: mongod --smallfiles
