version: '2'
services:
  onduty:
    image: onduty:1.1.7
    command: bundle exec puma -p 9292
    env_file:
      - onduty_config.env
    ports:
      - 9292:9292
    links:
      - mongodb:mongodbserver
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.4.4
    container_name: "mongodb"
    command: mongod --smallfiles --quiet
