version: '2'
services:
  onduty:
    build: .
    command: bundle exec puma -p 3000 -t 2:2
    env_file:
      - onduty-config.env
    ports:
      - 3000:3000
    links:
      - mongodb:mongodbserver
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.1
    container_name: "mongodb"
    command: mongod --smallfiles --quiet
