source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra', '~> 1.4.5'
gem 'sinatra-contrib', '~> 1.4.2'
gem 'sinatra-activerecord', '~> 2.0.2'
gem 'activerecord', '~> 4.1.6'
gem 'sqlite3'
gem 'puma'
gem 'rake'
gem 'twilio-ruby', '~> 3.13.1'
