require 'mongoid'
require 'sinatra'
require 'json'
require 'sinatra/contrib'
require 'sinatra/config_file'
require 'rack-flash'
require 'rack/contrib'
require 'erubis'

require 'onduty/version'
require 'onduty/config'
require 'onduty/notification'
require 'onduty/icinga2'
