development:
  # Configure available database sessions. (required)
  clients:
    # Defines the default session. (required)
    default:
      uri: <%= ENV['MONGODB_URI'] || "localhost:27017/onduty_production" %>
