############################
# Onduty Configuration File
#

# Secure onduty with simple auth
# admin_user:     admin
# admin_password: mySEcrtetPW

# Specify a mongoid.yml location (default is config/mongoid.yml)
# mongoid_config: /etc/onduty/mongoid.yml

base_url:       'http://localhost:3000/'

# session_secret: 'your?random!secret$'

# To find these visit https://www.twilio.com/user/account
account_sid: "12677267267267267627676276276276"
auth_token:  "32324323424242424242424242424242"
from_number: "+12345678910"

notification_plugins:
  - VoiceNotification
  - SmsNotification
  - MailNotification

# email_sender:   'alert@onduty'
smtp_options:
  :address: mail.example.com

icinga_cmd_path: /var/icinga/rw/icinga.cmd

# zendesk_url: https://yoursubdomain.zendesk.com/api/v2
# zendesk_username: you@yourdomain.com
# zendesk_token: you-zendesk-token
